name: Tests

on:
  pull_request:
    branches: ["*"]

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          extensions: mbstring, sqlite3, pdo_sqlite
          coverage: none

      - name: Copy .env
        run: cp .env.example .env

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v3

      - name: Generate application key
        run: php artisan key:generate

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Node dependencies
        run: npm ci

      - name: Build assets
        run: npm run build

      - name: Run tests
        run: composer run test
